// <auto-generated />
using System;
using BAERecruitmentProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAERecruitmentProject.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20251103215143_AddUniqueIndex_City_Timestamp")]
    partial class AddUniqueIndex_City_Timestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BAERecruitmentProject.Models.WeatherObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CityName", "ObservedAtUtc")
                        .IsUnique();

                    b.ToTable("WeatherObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
